# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /sustain/
title: Avinash Website/Blog
author: Avinash Nayak
description: Personal blog/website
avatar: profile.png
email: avinash8nayak@gmail.com
github: avinashnayak14 # username
#twitter: username
linkedin: avinash-nayak-40387198
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
